import Head from 'next/head'
import Container from '@mui/material/Container'
import Grid from '@mui/material/Grid'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Duranz Stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Grid container spacing={4}>
          <Grid item>
            <Typography variant='h3'>Welcome to Duranz Statistics System</Typography>
          </Grid>
          <Grid item>
            <Typography variant='h5'>Here you can find stats related to cricket. International matches and IPL, Big Bash</Typography>
          </Grid>
          <Grid item xs={12}>
            <Link href={'/player-stats'} >
              <Button sx={{ mr: 2 }} variant='outlined'>Check player stats</Button>
            </Link>
            <Link href={'/team-stats'} >
              <Button variant='outlined'>Check player stats</Button>
            </Link>
          </Grid>
        </Grid>
      </Container>
    </>
  )
}
